### ISSUE TITLE
 How to send a request to an actor without blocking?

### ISSUE THREAD

**Issue by sflyknife** [laforge49/JActor#18]
Hi...
I'm new to JActor2. Is there any way to send a request to an actor without blocking? I don't need any return value and I don't want to wait till the processing ends. Something like kilim's Mailbox.putnb(...);
Thank you!

**Comment by laforge49** [comment]
Well, you can always send an event. Then you will not get a response, but chances are, the thread will often go an process the request for you. :-)
http://jactor.sourceforge.net/JActor-2.1.0-9-MAR-2012/org/agilewiki/jactor/Request.html#sendEvent(org.agilewiki.jactor.Actor)

Now, regardless of whether you want a response or not, if you want the request to be processed on a different thread, then give the destination actor an asynchronous mailbox.
http://jactor.sourceforge.net/JActor-2.1.0-9-MAR-2012/org/agilewiki/jactor/MailboxFactory.html#createAsyncMailbox()

**Comment by laforge49** [comment]
OK, now why did I not provide something more fine grained than to force all requests from other actors sent to an actor with an asynchronous mailbox to be processed on a separate thread? Well, if you send a request to an actor that is going to take a long time, then all other actors/mailboxes/threads passing a request via a call to that actor will block. And if an actor blocks, then all the actors sharing the same mailbox are also blocked. So it is a dangerous situation. By forcing you to use an asynchronous mailbox (a very course grained solution), actors using different mailboxes can not pass requests via a call to that actor. We want to encourage the use of call, as it often improves both throughput and response time. So we want to arrange things so that dangerous situations are not common.

**Comment by laforge49** [comment]
Oops! My reasoning is a bit bogus. A synchronous call (which is really what I was talking about) can not be made in any case when the mailboxes of the two actors (request source and target) differ. So we could provide a more fine-grained means of forcing request processing to be on a different thread. So my justification really boils down to use cases, of which I see two:
1. The target actor is doing I/O.
2. Lots of computation within the actor to process the request.

I see these as exceptional use cases, where most request processing is either quick or spread over multiple actors. And I'm thinking that such exceptional cases should be isolated to separate actors with their own asynchronous mailboxes.

Of course, if you have another use case, I would be glad to hear it. We could, for example, create a new type of request which is always forced to be processed asynchronously. I am simply inclined not to provide features which I can not provide a use case for. :-)

**Comment by laforge49** [comment]
You may want to look at this: https://github.com/laforge49/JActor/wiki/Multithreading

In particular, take a look at the section "Forcing Asynchronous Operations".

**Comment by sflyknife** [comment]
Thanks so much for your help.
I'm trying JActor on an server which contains several services. Some services may handling the requests via RESTful protocol to get data from other machines. The server works with MINA2 NIO, so that it can handling the request and response asynchronously. I have to accept the reqeusts as quickly as I can and then deliver them to the right services. So I'm stucked in sending request to the service non-blocking.
I read about your replies and trying to make my project like below:

1). The dispatcher use a sync-mailbox to get and send one reqeust to the service at a time.(The sending operation should not be blocked)
2). Each service uses an async-mailbox so that all of they can proccess many request at the same time.
3). When process finished. The service send the result to the responsers for encoding the message into right format such as JSON or XML. Each responser also uses an async-mailbox.

Is that right?

**Comment by laforge49** [comment]
This sounds very right. I am also happy to provide some support in your endeavor. If you want, send your skype id to me, laforge49@gmail.com. I find that talking can help with some learning curves.

I would also give you a heads up that I am changing the API somewhat for requests, but your changes should be minor as I doubt that you have a lot of code that uses JActor right now. :-) (I expect to release version 2.2 RC2 today.)

**Comment by sflyknife** [comment]
Thank you very much!  JActor now is a very important component of my project. 

P.S. I have sent you a friend request on skype

**Comment by laforge49** [comment]
Skype contact accepted (unsolicited contact are not accepted for security reasons). Feel free to contact me any time. I work from home (retired) and tend to work more in the morning. And I'm living in India, so my timezone is +5:30. 

Very much looking forward to working with you.

Bill
