### ISSUE TITLE
Release binaries and sources Maven central

### ISSUE THREAD

**Issue by ydewit** [laforge49/JActor#2]
Not really a big deal in the short term, but it would be great if the binaries and sources could be found in Maven central. 

Another suggestion is to change the groupId to a fqn (org.jactor, etc) and have it lower-case, which seems to be a common Maven practice nowadays.

PS: Quite pleased to have come across this project.

**Comment by laforge49** [comment]
Glad you like it. I think I am doing something wrong though, as this project is receiving very little interest.

Bill
laforge49@gmail.com

**Comment by laforge49** [comment]
```
<groupId>org.agilewiki.jactor</groupId>
```

Pushed to GitHub.

**Comment by laforge49** [comment]
## William Edward La Forge Jr created OSSRH-2724:

```
        Summary: Lock-free Java Actors
            Key: OSSRH-2724
            URL: https://issues.sonatype.org/browse/OSSRH-2724
        Project: Community Support - Open Source Project Repository Hosting
     Issue Type: New Project
       Reporter: William Edward La Forge Jr
       Assignee: Juven Xu
```

JActor is a high-performance actor implementation in Java released under LGPL. It provides a more-than-reasonable alternative to programming with threads and locks.

No locks are used in the implementation of JActor, only a few semaphores, some concurrent data structures and a few atomic classes.

JActor achieves its speed, in part, by almost always executing synchronously--though it is easy enough to force asynchronous processing when needed. Messages are passed at a rate of 1 billion per second between actors sharing the same mailbox.

JActor is designed to make vertical scalability easy.

**Comment by BardurArantsson** [comment]
> I think I am doing something wrong though, as this project is receiving very little interest.

Speaking only for myself, it might have something to do with the lack of easy-to-approach examples/documentation :).

**Comment by ydewit** [comment]
Hi Bill,

I only recently (a few days) came across your project and I havent had
the time yet to properly evaluate it. However, two things stood out:

(1) documentation. I see that you do have some comments throughout the
code and documentation for the scala version of the project that
are/could be relevant here, but I could not find simple documentation
and code samples that could get someone from zero to 100 mph in 3
secs. I am specifically interested in simple examples of how to how to
create actors, wire them together and how to implement the different
type of interactions (request/reply, request one, reply many, publish,
subscribe (not the best example but a start:
http://code.google.com/p/jetlang/source/browse/#svn%2Ftrunk%2Fsrc%2Ftest%2Fjava%2Forg%2Fjetlang%2Fexamples%2Fdownload%253Fstate%253Dclosed
)

(2) performance. I don't have an extensive experience with the Actor's
model, but the idea of multiple actors sharing a mailbox, or modeling
a req/resp interaction directly in the framework, for instance, seems
interesting to say the least.

Before finding JActor I looked through a bunch of different frameworks
(Java only) and ended up with Jetlang (many of the options are either
not Java or seem to provide much more than I wanted to like e.g. code
weavers, trying to extend the Java language - I don't want a framework
that tries to fix Java, but one that has a simple and clear way to
achieve what is needed).  It like Jetlang because of it's simplicity
(I don't want/need the kitchen sink, just the minimal touch points to
get implementations done, or at least the choice to pull in only what
I need/want). I also tend to favor static-typing as much as possible
and Jetlang allows me to designed the Actor veneer on top of it the
way I would like to.

For the most part and seems that JActor could be an interesting
alternative to my needs and I would be willing to give it a try (and
any feedback along the process if you are interested). This brings
back to having a set of simple examples focused on Actor's (FP
constructs or statemachine, etc, are interesting but would not be my
first focus).

my 2 cents,
-- yuri

On Tue, Jan 17, 2012 at 11:12 AM, BardurArantsson
reply@reply.github.com
wrote:

**Comment by laforge49** [comment]
Examples I can do. There are few in the javadocs, but I can add a lot more.

For the moment, you will find a LOT of uncommented examples in the tests, which can be found in both the GitHub repository and in the download. For example, the test for Event: https://github.com/laforge49/JActor/blob/master/src/test/java/org/agilewiki/jactor/lpc/EventTest.java

Many thanks for the feedback. --Bill

**Comment by laforge49** [comment]
I've now added an introduction to JActor in the package-info.java file for the jactor package. Documentation takes time, but it is a start. This will be on-line in the next release, but for now it is available in the GitHub and can be accessed here: https://raw.github.com/laforge49/JActor/master/src/main/java/org/agilewiki/jactor/package-info.java

It has also occurred to me that I can add links to the tests in the javadocs, making them easy to access where appropriate. Might as well make the best use of the code that already works.

On another front, the code for JActor is pretty much done, the final piece being full support for 1-way messages. (The send method no longer requires a ResponseProcessor parameter and the actor logic has been optimized to take full advantage of this.) So it is a matter of doing the docs, providing occasional enhancements, and spawning new projects that leverage JActor.

Hopefully once the docs are in better shape there will be some interest in working on some projects with me. There is WAY TO MUCH TO BE DONE for one person!

Bill

**Comment by laforge49** [comment]
Thinking about pub/sub. Now that 1-way messaging is fully supported, a high-performance pub/sub is trivial to implement. So much so that I'm thinking that it might be a first project for someone else to develop once the docs are up-to-speed.

For pub/sub you just need to write a subclass of Component. It will need a concurrent data structure to track subscriptions. And three types of messages: subscribe, unsubscribe and publish. 

All three message bindings would use SuncBinding. And messages sent by the publish logic would all be 1-way.

Should be quite fast, both when subscribers use the same mailbox and when subscribers are asynchronous. Hmm. Perhaps I need to drop synchronous processing across mailboxes as there are cases where it creates problems. I should also think deeper about sharing asynchronous mailboxes.

Anyway, what I'm saying is that I should focus on the docs for now, with the hope of building community.

Optimistic as always.

Bill

**Comment by BardurArantsson** [comment]
The documentation you should be of great help for those getting started. Kudos.

**Comment by laforge49** [comment]
Just did release 1.3.0, which includes a tutorial for JLPCActor: http://jactor.sourceforge.net/org/agilewiki/jactor/lpc/package-summary.html#package_description

Also I decided to take the hint and added publish/subscribe. It is a bit slower than straight messaging at 80 million publications per second.

**Comment by laforge49** [comment]
This has been successfully closed: https://issues.sonatype.org/browse/OSSRH-2724?focusedCommentId=148842#comment-148842

So with some luck and a bit of effort on my part we will soon have a maven repository for JActor and I can close this issue.

**Comment by laforge49** [comment]
I managed to push out a snapshot, but Sonatype still needs to review the artifacts and activate central sync for me.

**Comment by laforge49** [comment]
We are on central: http://search.maven.org/#search|ga|1|g%3A%22org.agilewiki.jactor%22
