### ISSUE TITLE
Comparing classes with == is slow and incorrect

### ISSUE THREAD

**Issue by kumarshantanu** [laforge49/JActor#21]
At a number of places in the codebase `==` is used to compare classes for equality, which is both slow and incorrect. It is incorrect because it wouldn't work with proxies where a new proxy sub-class is created at runtime. Examples: CGLIB proxy, JVM proxy, Spring-AOP integration etc.

A possible fix is to use `instanceof` where the exact reference class is known beforehand, or to use `class1.isAssignableFrom(class2)`. In a single-threaded experiment I did on a quad-core Intel i7 based Macbook Pro, I got the following mean numbers with a warmed JVM:

```
class1 == class2                        | 2.747921 us
obj instanceof class1                   | 2.743640 us
class1.isAssignableFrom(class2)         | 2.741118 us
obj.getClass().isAssignableFrom(class2) | 2.781485 us
```

**Comment by laforge49** [comment]
This change is subsumed by https://github.com/laforge49/JActor/issues/26
