### ISSUE TITLE
so less document

### ISSUE THREAD

**Issue by siruyi** [laforge49/JActor#31]
so less document , i want to learn the jactor but i have no lots of time to watch the code ,and the important,i 'm week of code skill,so it's hard to learn for me . 
      when i search the actor , out look of the akka and kilim, the jactor is the most come out ,i think it's the right thing i want.but i can't know how to use it .
see http://www.ibm.com/developerworks/library/j-javaactors/j-javaactors-pdf.pdf,it's what i want to see

**Comment by laforge49** [comment]
Have you seen this? https://github.com/laforge49/JActor/wiki/JActor-Basics

**Comment by siruyi** [comment]
Bill：
     Thanks for your latter,i'm so appreciate, it's the first time i got a email from abroad that's not an ad.
 the wiki i'v seen a few times ,in the same time , i got the github code an  test them one by one ,but can't get in,
 i 'm poor ,i just want there a more explanation and more example.sorry.

 ------------------ 原始邮件 ------------------
  发件人: "Bill La Forge"reply@reply.github.com;
 发送时间: 2012年6月12日(星期二) 中午1:44
 收件人: "siruyi"rose8012130@126.com; 

 主题: Re: [JActor] so less document (#31)

Have you seen this? https://github.com/laforge49/JActor/wiki/JActor-Basics

---

**Comment by laforge49** [comment]
http://sourceforge.net/projects/jactor/files/Code%20Samples%2012-JUN-2012.pdf/download

The above is mostly a rewrite, but you might find it a bit clearer. And there are a few extra examples too.

**Comment by siruyi** [comment]
thanksgiving。谢谢 `_` 好人呐。。。

**Comment by learning** [comment]
@laforge49 能看懂么?

**Comment by siruyi** [comment]
哈哈哈哈哈，你这句话能从很多角度去理解。不过 i'm shame!!!

**Comment by laforge49** [comment]
My twitter id is @laforge49, if that is what you are asking.

**Comment by siruyi** [comment]
to be a twitter , we v to scroll over the china great wall . the gov wall.

**Comment by siruyi** [comment]
larforge , he just want to ask you if you can understand what i say .Hehehe...

**Comment by learning** [comment]
@laforge49 , @siruyi says you're so nice. :)

**Comment by laforge49** [comment]
Well, there are a lot of downloads from China. It is good to hear from some of you.

I am from the US, but living in Bangalore, India. Not so many downloads from India.

**Comment by learning** [comment]
My friend [sflyknife](https://github.com/sflyknife) also using  JActor. :)
