### ISSUE TITLE
API betterment- Optimal number of threads for Async mailbox

### ISSUE THREAD

**Issue by anirbanbhattacharjee** [laforge49/JActor#34]
Statement:
Consider the below code :

```
        // Please refer org.agilewiki.jactor.basics.Test5 for the complete program
        MailboxFactory mf = getMailboxFactory();
        Actor5 a = new Actor5();
        a.initialize(mf.createAsyncMailbox());
        Actor5 b = new Actor5();
        b.initialize(mf.createAsyncMailbox());
        Actor5 c = new Actor5();
        c.initialize(mf.createAsyncMailbox());
        a.delay = 10;
        c.delay = 10;
        a.delay = 10;
        final long t0 = System.currentTimeMillis();
        RP<Object> rc = new RP<Object>() {
            int c = 3;

            @Override
            public void processResponse(Object response) throws Exception {
                c -= 1;
                if (c == 0) {
                    long t1 = System.currentTimeMillis();
                    System.out.println("Time taken-->" + (t1 - t0));
                    rp.processResponse((t1 - t0) <= 30);
                }
            }
        };
        Delay.req.send(this, a, rc);
        Delay.req.send(this, b, rc);
        Delay.req.send(this, c, rc);
```

The timing test will yield best output for the following definition of MailboxFactory-

```
    MailboxFactory mailboxFactory = JAMailboxFactory.newMailboxFactory(3);  // creates 3 threads for 3 async mailboxes
```

Whereas, with 1 or 2 threads (JAMailboxFactory.newMailboxFactory(1) or  JAMailboxFactory.newMailboxFactory(2)), it is not going yield optimal output. 

Problem : 
End user's program may be dynamic in nature. How about making the MailboxFactory  initialization intelligent, so that based on a given problem it will spawn optimal number of threads automatically.

**Comment by laforge49** [comment]
The number of threads needs to be set to

the number of hardware threads on your computer
+
The number of actors which may block at the same time.

On the other hand, setting the number of threads high (but not real large)
has almost no negative impact.

Perhaps we could just use a default value of 100 and be done with it for
99% of the cases. :-)

Bill

On Sun, Jun 24, 2012 at 8:13 PM, Anirban Bhattacharjee <
reply@reply.github.com

**Comment by anirbanbhattacharjee** [comment]
The 2nd element(**_The number of actors which may block at the same time**_) of the RHS of equation,

```
Number of threads = The number of hardware threads on your computer + The number of actors which may block at the same time.
```

may be different for different scenarios. If we rather simplify the equation

```
// Number of threads = The number of hardware threads on your computer 
JAMailboxFactory.newMailboxFactory(Runtime.getRuntime().availableProcessors());
```

In blocking actor scenarios are we going to see significant performance deterioration?

**Comment by anirbanbhattacharjee** [comment]
Sorry, please skip the previous post, I overlooked the following-

---

On the other hand, setting the number of threads high (but not real large) has almost no negative impact. Perhaps we could just use a default value of 100 and be done with it for 99% of the cases. :-) 

---

But, I have observed that, setting an arbitrary high value doesn't yield least time complexity.

**Comment by laforge49** [comment]
Interesting. I haven't experimented with it except that I didn't observe
any noticeable degrading with just a few extra threads.

Note that if you allocate 10 threads and there are 10 or more actors which
block, then all processing stops. So it is vital that there be enough
threads.

On the other hand, if we add a thread when we need one we might be OK as
JActor tries really hard never to use a thread except when an asynchronous
mailbox is encountered. Ah, but that depends on how the application is
architected. In the case of a web server, we could allocate thousands and
thousands of threads needlessly.

Perhaps we should allocate automatically but with a limit? Gosh, now we're
getting back to all the complexities of those slow thread pools included in
the JDK.

Lets do the KISS thing for now. And allow developers to use the JDK thread
pools to address the problems they face, or roll their own. So all we
really need to do is change JAThreadManager to use the standard interface.
Don't over-engineer the solution!

Bill

On Sun, Jun 24, 2012 at 9:38 PM, Anirban Bhattacharjee <
reply@reply.github.com
