### ISSUE TITLE
Help: How can I make jactor cancelable or timeout feature?

### ISSUE THREAD

**Issue by qxo** [laforge49/JActor#36]

**Comment by laforge49** [comment]
One thing to keep in mind is that for any given request there can be only one response or exception thrown.So if actor X, while processing request x sends a request y to actor Y, but Y does not respond quickly enough for X, X can simply respond to the x request with a timeout, optionally raising a flag that the response to request y should be ignored.

Now lets say we have a timer actor T. When X gets an x and sends a y to Y, it can also send a t to T. This is easily done by simply having 2 consecutive sends--parallelism is the default. X can then treat the response to t as a timeout.

**Comment by qxo** [comment]
Thanks:) 
Can you write some example code for this case(cancelable or timeout feature) ?

**Comment by laforge49** [comment]
```
public class X extends JLPCActor {
    public Y doer;
    public T timer;

    public void x(RP rp) {
        Doit.req.send(this, doer, rp);
        (new Delay(1000)).send(this, timer, rp);
    }
}
```

Assumption: timer and doer both use async mailboxes. This way the Doit and Delay requests are processed "in parallel". X then returns the result from whichever completes first.
