### ISSUE TITLE
Benchmark tests needed

### ISSUE THREAD

**Issue by akaigoro** [laforge49/JActor#37]
The project contains a lot of unit tests, but no benchmarks supplied. As a result, it is hard to make sure the library is as fast as claimed.

**Comment by laforge49** [comment]
The benchmarks are there, mixed in with the unit tests. Case in point: https://github.com/laforge49/JActor/tree/master/src/test/java/org/agilewiki/jactor/lpc/timingTest

Consider for example, https://github.com/laforge49/JActor/blob/master/src/test/java/org/agilewiki/jactor/lpc/timingTest/AsyncMailboxTest.java

look at the code
         int c = 2;
        int b = 3;
        int p = 1;
        int t = 1;

```
    //System.out.println("####################################################");
    //int c = 500;
    //int b = 1000;
    //int p = 1000;
    //int t = 8;

    //burst size of 100
    //1000 parallel runs of 1,000,000 messages each.
    //1,000,000,000 messages sent with 8 threads.
    //msgs per sec = 81,083,272
```

Here you need to comment the first 4 lines of code and uncomment the next few to run the test.

Bill
