### ISSUE TITLE
Should we use logging instead of system.out.print

### ISSUE THREAD

**Issue by weejulius** [laforge49/JActor#39]
Hi,

The JLPCAtor use system.out.println to print the exception message, it is not so convenience to figure out where the exception is from. it might use logging like slf4j.

Thanks

Julius

**Comment by weejulius** [comment]
It seems if the request is event, we could not throw  exception in the exception handler. and the exception handler will catch and print.

Could we let the exception handler to decide if the exception is print or thrown?

**Comment by laforge49** [comment]
We will want to be a bit careful about how we do logging, as different projects may want to use different loggers. I think the best approach would be to extend the API of MailboxFactory, which users can easily override with their preferred logger.

As for letting the exception handler decide what to do with an exception, I thought that that was the way it already works. Only when there is no exception handler present and the request was passed as an event should we be printing the exception. I can review this next week when I get back to India.

**Comment by laforge49** [comment]
See https://sourceforge.net/p/jactor/blog/2012/09/available-for-download-jactor-410-jid-140-jfile-205/
