### ISSUE TITLE
is this framework support for remoted actor model?

### ISSUE THREAD

**Issue by pinopino** [laforge49/JActor#40]
as the title.

**Comment by laforge49** [comment]
The JASocket package is half done and will support passing serialized actors. The JID package already support the serialization of actors--in deed, it only serializes subclasses of the Jid actor.

I have been thinking about creating a bindery which would support the location of resources, and that would include support for sending messages to remote actors.

Unfortunately, though I am working on this full time, things are going slowly. My current focus is on documenting how to use JID. Hopefully having good documentation will encourage contributions, which explains my emphases on documentation.

In the incarnations prior to JActor, I was always in a mad rush to complete functionality, and ended up with a really super demo and nothing else.
